# Generated by Django 4.2.28 on 2026-02-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, help_text='Department for department staff', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_department_user',
            field=models.BooleanField(default=False, help_text='Whether this user is a department staff member'),
        ),
    ]
