# Generated by Django 4.2.28 on 2026-02-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='department',
            field=models.CharField(blank=True, help_text='Department responsible for this category', max_length=100),
        ),
    ]
